#!/bin/bash
# external tools are found in ~/.config/gedit/tools
# tool file permission requires read-write and 'allow executing file as a program'
# [Gedit Tool]
# Input=document
# Output=output-panel
# Applicability=all
# Save-files=nothing

stdin=$(cat)
echo "$stdin" | gpg -d --no-tty - 2> /dev/null

