#!/bin/bash
# external tools are found in ~/.config/gedit/tools
# tool file permission requires read-write and 'allow executing file as a program'
# [Gedit Tool]
# Name=g-encrypt-ssl-file-key
# Applicability=all
# Output=replace-document
# Input=document
# Save-files=nothing

stdin=$(cat)
#key=$(bash ~/bin/getFile.sh)
file=$(zenity --file-selection)
echo "$stdin" | openssl aes-256-cbc -md sha256 -e -a -pass file:"${file}"

