#!/bin/bash
# external tools are found in ~/.config/gedit/tools
# tool file permission requires read-write and 'allow executing file as a program'
# [Gedit Tool]
# Name=g-encrypt-ssl-pw
# Applicability=all
# Output=replace-document
# Input=document
# Save-files=nothing

stdin=$(cat)
pw=$(zenity --entry --text="passphrase" --entry-text="passphrase")
echo "$stdin" | openssl enc -aes-256-cbc -salt -a -pass pass:"${pw}"

